version: '3'
services:
    nginx:
      image: affordability/nginx
      build:
        context: ./
        dockerfile: ./deploy/nginx.dockerfile
      ports:
        - "80:80"
      depends_on:
        - api
      logging: &logging
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
      restart: always
    api:
      command: uwsgi --ini /api/uwsgi.ini
      environment:
        - FLASK_ENV=production
      logging:
        <<: *logging
      restart: always
